"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
# -*- encoding:utf-8 -*-
from setuptools import setup
from setuptools import find_packages

APP = ['src/kindleHelper.py']
APP_NAME='kindleHelper'
DATA_FILES = ['src/assets/add.png', 'src/assets/stop.png', 'src/assets/create_task.png', 'src/assets/book.png', 'src/assets/download.png', 'src/assets/push_selected.png', 'src/assets/wx.jpg', 'src/assets/tengxun.png', 'src/assets/zip.png', 'src/assets/file.png', 'src/assets/download_btn.png', 'src/assets/done_selected.png', 'src/assets/about_selected.png', 'src/assets/search.png', 'src/assets/find.png', 'src/assets/done.png', 'src/assets/baidu.png', 'src/assets/logo.png', 'src/assets/upload.png', 'src/assets/push.png', 'src/assets/delete.png', 'src/assets/search_selected.png', 'src/assets/send_selected.png', 'src/assets/pdf.png', 'src/assets/add_selected.png', 'src/assets/kindle.png', 'src/assets/About.png', 'src/assets/chengtong.png', 'src/assets/message_success.png', 'src/assets/reward.jpg', 'src/assets/send.png', 'src/assets/download_selected.png','src/kindle.icns']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'kindle.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "kinleHelper By Leetao",
        'CFBundleIdentifier': "com.gmail.cn.leetao94",
        'CFBundleVersion': "1.1.0",
        'CFBundleShortVersionString': "1.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2020, Leetao, All Rights Reserved"
    },
    'includes':['PyQt5',"sip"]
}

setup(
    name=APP_NAME,
    app=APP,
    packages=find_packages("src"),
    package_dir={"": "src"},
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
